### PR TITLE
ModalWindow: Migrate from zeus::clamp to std::clamp

### PR DESCRIPTION
**Pull request by lioncash**
Migrates to standard library facilities.

---
This change is [Reviewable](https://reviewable.io/reviews/axiodl/specter/9)

### CODE REVIEW

**Comment by Antidote** [comment]
I'm not merging this, we use `zeus::clamp` because we prefer the argument order.

**Comment by lioncash** [comment]
Keep in mind that decision will indeed act as a potential footgun for new contributors. Most contributors outside the project will likely be exposed to `std::clamp` first and expect the argument order to behave like it, allowing logic bugs to potentially slip through.

**Comment by Antidote** [comment]
They'll get a compile error if they attempt to.

**Comment by lioncash** [comment]
They will [not](https://godbolt.org/z/ydUPge)

**Comment by Antidote** [comment]
I'll go ahead and merge this PR for specter, but I will not accept any for URDE, `zeus::clamp` was written with the order it has for a specific reason beyond preference.

**Pull request merged**
